### ISSUE TITLE
Compiler warning on DMD

### ISSUE THREAD

**Issue by Tuz550** [trikko/vasaro#6]
The following warning is thrown when compiling using DMD-2.094.2 (x64, Windows) and dub-v1.23.0-windows-x86_64:

`C:\Users\Admin\AppData\Local\dub\packages\gtk-d-3.8.5\gtk-d\generated\gtkd\glib\Spawn.d(305,3): Deprecation: foreach: loop index implicitly converted from size_t to int`

Compliation appears to freeze at this point. Suspect line may be in generator.d, ln 264 (code uses size_t instead of int). I don't know D, so I'm unsure what best coding practice is in this case.

When compiled using LDC2 (LDC-1.24.0-windows-x64), I get deprecation warnings on every line of every file as follows:

`C:\Users\Admin\AppData\Local\dub\packages\gtk-d-3.8.5\gtk-d\generated\gtkd\rsvg\c\functions.d(67,2): Deprecation: template gtkd.Loader.Linker.link(T)(ref T funct, string symbol, LIBRARY[] libraries...) is deprecated - Use the LIBRARY_* symbols defined for each package, instead of gtkd.paths.LIBRARY`

When the program attempts to execute following compilation, it exits with code -1073741819.

I don't know if my environment is poorly set up (entirely possible), but I'm not having luck with either compiler. Compilation attempted on Windows 10 v2004 on an x86_64 system with an Intel i7-6700HQ.

**Comment by trikko** [comment]
Hi there, thank you for your time.  

> The following warning is thrown when compiling using DMD-2.094.2 (x64, Windows) and dub-v1.23.0-windows-x86_64:
> 
> `C:\Users\Admin\AppData\Local\dub\packages\gtk-d-3.8.5\gtk-d\generated\gtkd\glib\Spawn.d(305,3): Deprecation: foreach: loop index implicitly converted from size_t to int`
> 
> Compliation appears to freeze at this point. Suspect line may be in generator.d, ln 264 (code uses size_t instead of int). I don't know D, so I'm unsure what best coding practice is in this case.

So this is a problem of the library gtk-d I use to build the GUI. Indeed they use int instead of size_t. That's not the right way.
The length of an array is long for 64-bit machines and int for 32-bit machines.
size_t in D is an alias. On 32-bit machines size_t == int, on 64-bit machines size_t == long and you should use size_t every time you're counting something or working with (array) length.  Anyway it's just a warning, it should not create any problem in this case.

This code:
```d
int a = myarray.length;
```
triggers a warning on 64-bit machine

This:
```d
long a = myarray.length;
```
triggers a warning on 32-bit machine

This:
```d
size_t a = myarray.length;
```
works fine in both cases.

gtk-d is a huge library, so I guess it can take a long time to compile (just the first time). Probably you just need to wait for it to compile.
The app itself should compile in just a few seconds using dmd when gtk-d is ready.

Keep me posted about this.

> 
> When compiled using LDC2 (LDC-1.24.0-windows-x64), I get deprecation warnings on every line of every file as follows:
> 
> `C:\Users\Admin\AppData\Local\dub\packages\gtk-d-3.8.5\gtk-d\generated\gtkd\rsvg\c\functions.d(67,2): Deprecation: template gtkd.Loader.Linker.link(T)(ref T funct, string symbol, LIBRARY[] libraries...) is deprecated - Use the LIBRARY_* symbols defined for each package, instead of gtkd.paths.LIBRARY`
> 
> When the program attempts to execute following compilation, it exits with code -1073741819.
> 
> I don't know if my environment is poorly set up (entirely possible), but I'm not having luck with either compiler. Compilation attempted on Windows 10 v2004 on an x86_64 system with an Intel i7-6700HQ.

That's strange. A question: do you have an accelerated 3d card on your machine?

**Comment by Tuz550** [comment]
> gtk-d is a huge library, so I guess it can take a long time to compile (just the first time). Probably you just need to wait for it to compile. 

OK, I'll retry later. 

> That's strange. A question: do you have an accelerated 3d card on your machine?

Yes, I have an Nvidia GTX 1060 Mobile chipset.

**Comment by Tuz550** [comment]
Hi, I've just retried compliation using DMD; I've left it for about a day and it's still not compiling the library. LDC2 did complete compilation and I was able to execute the program after including the SDL2 library and GTK3.
